# Optional:
#
# Secret for access to a private image registry. Necessary in case your Kubeflow pipelines consume private images. 

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-project-com-credentials
  namespace: kubeflow
spec:
  encryptedData:
    .dockerconfigjson: ''
  template:
    metadata:
      creationTimestamp: null
      name: registry-project-com-credentials
      namespace: kubeflow
    type: kubernetes.io/dockerconfigjson