# Optional:
#
# Secret for access to a private image registry. Necessary in case your Kubeflow pipelines consume private images. 

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-project-com-credentials
  namespace: kubeflow
spec:
  encryptedData:
    .dockerconfigjson: AgBa8SNhEJzYrwElXdw9qmrL7Qm4I/v2aVjxC9tQmA4569nI9Oe9ylXoc2jTT06dZFi7M+GBkg1pejwALQryDSFrM+qFV77y++9lOmqHfd80aJRtj/e8BA+fvMubjeiZA2fCWoe2i37p1PHKtYkkq6uaTgxLOCllxNFlMpzj/YUdUE8F/yfCggBxEs0YDQ0zkqYchE7vCWQ5r5QVxglN6rLADn5/yOO7fLCz6INmKKQ3Wf97T/agoQPiSbKFa8LqQiixco7yQdp51s2h9aJvSsFPkL47B78rmlpcSdpYNQleKqMXozFtYWC2j5LJMQkxH/mephFrjB8PVdY/xkmX/XOH4XYVA3sDWDPE1MigIn2Qi2NJ2yFeVxNNOBD0d8Hy+bltJnWrf+t7qg3lHEBvUb6oSguzquUx9PqS3SSBVqOM6l0sHXaTMgJzJNko/qlLLQP2rK0eUN4PeqBFvc2hqiYlsy8wdDG+ob4K7Q1Ps/LC9Wf8MFLa58PP5J9ojcY5jX9KGUX4X94foqKVeJID7cintcczgRh/IIs9AvRxz7BbXMj1Y1CJhWDbGhS4+bFnoKBcvRO5G8hZI6rR9e2322NEbopJ012ZZk1wTCaeMmY25GJW+GxrASYRIdh1V0xzfQjJXnSe+VS9GwFLW0iqVcBkzeMJZLUoy3fjpco9Y9vmmUNoCI9x7uSRCm407TprTNgKMQNpfYZq3l7XWwipVgCsUYR54uSyoBddnaBgSqe5Ir77kOgc7od2E3eCotHhGFQTBsA+DYmK8xJy0r5LpL7ylnEx102DoOaejoEZiQCNgxNyuRGSgsFYX2q1BJq0PB/b0tcRiLuCa9YSAS+xb580xnpcgDQkoM1PjwFxQAcVCecPBofR1AnkN0aUWLAFjm5hAJM119vYihDPCju2AhQhUbrBLZgOgjlUnItF94bLgP5MexYRFGl1aKqYir9OOr54ZDHdKOJjag5tuhX9KkManhiV6ks7bGiiogqin6jXgx8qnQHANMHMrZCRy6WDkE2tyYIab2GSRljezL/MaeJ1nexF+kS0fi+IvaQtSG546ePY5tjb0pdrZF6PbeL4yWPyhoikkEl0
  template:
    metadata:
      creationTimestamp: null
      name: registry-project-com-credentials
      namespace: kubeflow
    type: kubernetes.io/dockerconfigjson