apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: flux-system
spec:
  releaseName: node-problem-detector
  targetNamespace: node-problem-detector
  storageNamespace: node-problem-detector
  interval: 5m
  chart:
    spec:
      chart: node-problem-detector
      version: 2.3.13
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
        namespace: flux-system
      interval: 1m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    networkPolicy:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi