apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  targetNamespace: sealed-secrets
  storageNamespace: sealed-secrets
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.15.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      interval: 1m
  values:
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi