---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: gemini
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-problem-detector
---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: promtail
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-autoscaler
---
apiVersion: v1
kind: Namespace
metadata:
  name: ebs-csi-driver