apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-mountpoint-s3-csi-driver
  namespace: flux-system
spec:
  releaseName: aws-mountpoint-s3-csi-driver
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: aws-mountpoint-s3-csi-driver
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: aws-mountpoint-s3-csi-driver
        namespace: flux-system
      interval: 1m
  values:
    awsAccessSecret:
      name: aws-mountpoint-s3-csi-driver-credentials
      keyId: AWS_ACCESS_KEY_ID
      accessKey: AWS_SECRET_ACCESS_KEY
    node: 
      tolerations: 
        - key: "kubeflow/cpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"