apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autoscaler
  namespace: flux-system
spec:
  releaseName: autoscaler
  targetNamespace: kube-system
  storageNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: cluster-autoscaler
      version: 9.37.0
      sourceRef:
        kind: HelmRepository
        name: autoscaler
        namespace: flux-system
      interval: 1m
  values:
    autoDiscovery:
      clusterName: frankfurt.kubeflow.project.com
    awsRegion: eu-central-1
    envFromSecret: autoscaler-aws-credentials
    expanderPriorities: |-
      40: 
        - .*m7i-large.*
      30: 
        - .*m7i-xlarge.*
      20: 
        - .*m7i-2xlarge.*
      10: 
        - .*m7i-4xlarge.*
    extraArgs:
      expander: priority
      