apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gemini
  namespace: flux-system
spec:
  releaseName: gemini
  targetNamespace: gemini
  storageNamespace: gemini
  interval: 5m
  chart:
    spec:
      chart: gemini
      version: 2.1.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: flux-system
      interval: 1m
  values:
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 50Mi