apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  releaseName: gpu-operator
  targetNamespace: gpu-operator
  storageNamespace: gpu-operator
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      version: v24.3.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 1m
  values:
    dcgmExporter:
      serviceMonitor:
        enabled: true