apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  releaseName: kube-prometheus-stack
  targetNamespace: prometheus
  storageNamespace: prometheus
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 60.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1m
  values:
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      agentMode: true
      prometheusSpec:
        remoteWrite:
          - url: https://metrics.project.com/api/v1/push
            headers:
              "X-Scope-OrgID": ''
        serviceMonitorSelectorNilUsesHelmValues: false